# Generated by Django 3.2.12 on 2022-02-16 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Son',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=60)),
                ('second_name', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=12)),
                ('age', models.IntegerField()),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.elder')),
            ],
        ),
    ]
