# Generated by Django 3.2.12 on 2022-02-16 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='son',
            name='age',
        ),
    ]
