# Generated by Django 3.2.12 on 2022-02-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_son'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='son',
            name='elder',
        ),
        migrations.AddField(
            model_name='son',
            name='elder',
            field=models.ManyToManyField(to='api.Elder'),
        ),
    ]
