# Generated by Django 3.2.12 on 2022-02-16 11:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220216_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proffesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
            ],
        ),
        migrations.AlterField(
            model_name='elder',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='son',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Pro',
            fields=[
                ('first_name', models.CharField(max_length=60)),
                ('second_name', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('phone_number', models.CharField(max_length=12)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profession', models.ManyToManyField(to='api.Proffesion')),
            ],
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(verbose_name=False)),
                ('description', models.CharField(max_length=1024)),
                ('elder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.elder')),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pro')),
                ('son', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.son')),
            ],
        ),
    ]
